### ISSUE TITLE
Materials

### ISSUE THREAD

**Issue by Armintron** [ctcuff/CAP4720-final-project#18]
Includes texture mapping, specularity, ambience, and diffuseness(?)

**Comment by Armintron** [comment]
Is this done?

**Comment by AlexanderLongo** [comment]
texture mapping is done, not sure if we are using specularity ambience and diffuseness. If we are then I can wrap all these up into a materials class. If not then we can close the issue.

**Comment by TheIceCreamBear** [comment]
> not sure if we are using specularity ambience and diffuseness.

Having these scalars in the material class and then being passed into the shader would be nice.

**Comment by AlexanderLongo** [comment]
Ok will make the change and do a pr
